---
title: "2025-01-03"
date: 2025-01-03T18:45:14+09:00
author: "Naoya Furudono"
draft: false
tags:
    - daily
    - PL
    - tech
    - idea
---

# Goでエラーにスタックトレースつけるの楽じゃなさそう

[k1LoW/errors](https://github.com/k1LoW/errors) でスタックトレースをエラーにつけられるようになる。
便利なのだがトレースをプログラマが明示的に指示しないといけない。設定を一回すれば終わりではなく忘れずに繰り返す必要があるのが辛い。
その漏れをどのようになくすかを考える。

## 背景・既存のアイデア

まず、どのように設定する必要があるかを整理する。
エラーを例外として捉えるとその発生源でトレースの取得をする必要があると理解できる。
ここで発生源として扱うのは、ユーザが管理しうるコードベースの範囲内に限る。例えば標準ライブラリの関数がエラーを返したとしても、その中に発生源があるとは思わない。
発生源はそのエラーを返した標準ライブラリの関数の呼び出しをするコードである。
以下のサンプルコードではstringsパッケージのBuilder.Writeを呼び出している。そのメソッド呼び出しが発生箇所となりうる。

```go
package main

import "strings"

func f() error {
	b := strings.Builder{}
	_, err := b.Write([]byte("hello"))
	if err != nil {
		return err
	}
	// ...
}
```

スタックトレースを取りたい場合、この発生源でスタックトレースを取得したい。k1LoW/errorsを使うと以下のように書ける。

```go
package main

import (
	"strings"
	
	"github.com/k1LoW/errors"
)

func f() error {
	b := strings.Builder{}
	_, err := b.Write([]byte("hello"))
	if err != nil {
		return errors.WithStack(err)
	}
	// ...
}
```

名前付き返り値とdeferを使って忘れないようにする手法も紹介されている。

```go
func f() (err error) {
	defer (func(){
		err = errors.WithStack(err)
	})()
	b := strings.Builder{}
	_, err := b.Write([]byte("hello"))
	if err != nil {
		return err
	}
	// ...
}
```

## 課題

deferを毎回設定するために注意するのが辛い。コンパイラに怒ってもらうとか、linterに注意してもらいたい。
そもそもエラーオブジェクトの生成はランタイムの仕事にして、ライブラリだろうがなんだろうがコールスタックを取ってくれると嬉しいのだけど。

新しくクライアント側でインターフェースを宣言して、標準のerrorインターフェースに加えてStackTracesメソッドを呼べることを要求すれば良い？とも思ったが厳しそう。
この案に乗っかる場合、全ての関数定義でエラーを返す代わりに新しく定義した型を返す。
普通にerrorを返すとStackTracesメソッドを実装してないので型エラーになって落ちる。

機能はするのだが、deferを使う戦略が汚くなるのが辛い。
deferで呼ぶ関数の中で戻り値のerror型の値にスタックトレースを付け足す戦略がdefer戦略なので、deferを使うためには関数の戻り値がerrorになることは許容する必要がある。
とはいえ、全ての `return err` を `return errors.WithStack(err)` に書き換えれば済むし、それはコンパイラが強制してくれるのでどうにもならないことはない。

リンターを書けばなんとかなるのはそう。検証内容は以下。

- 戻り値にエラーが含まれるトップレベルでの関数定義を列挙して、全てが以下を満たすことを検証する
  - エラーの戻り値に名前がついていること(errとする)
  - defer文を列挙する。いずれか一つが以下を満たすことを検証する
    - err = errors.WithStack(err) が実行されること

偽陽性が入る余地多いけど、割とカバーできそう。除外のための設定くらいは入れてもいいかもしれない。

# 掃除

大掃除は年末にしたのだけど、コーヒーグラインダーを掃除し忘れていたのでやった。
結構な量の粉が中から出てきて驚いた。豆を砕く場所と粉が出てくる穴の間に傾斜した通路があってそこに溜まっていた。
